<?php

namespace TeamBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPseudoLike( $pseudo, $inTeam = false ) {
        $qb = $this->createQueryBuilder( 'p' );
        $qb->select( 'p.pseudo' );
        $qb->where($qb->expr()->andX()
            ->add( 'p.pseudo LIKE ?1')
            ->add( $inTeam ? 'p.team IS NOT NULL OR p.team IS NULL' : 'p.team IS NULL' )
        );

        $qb->setParameter( '1', '%'.$pseudo.'%' );

        return $qb->getQuery()->getScalarResult();
    }

    public function search( $terms ) {
        $qb = $this->createQueryBuilder( 'p' );

        for( $i = 0; $i < count( $terms ); $i++ )
            $qb->orWhere( $qb->expr()->andX()->add( 'p.pseudo LIKE ?'.$i )->add( 'p.team IS NOT NULL' ) );

        $qb->setParameters( $terms );

        return $qb->getQuery()->getResult();
    }

    public function findPlayerWithoutTeam( $pseudo ) {
        $qb = $this->createQueryBuilder( 'p' );
        $qb->select( 'p.pseudo' );
        $qb->where($qb->expr()->andX()
            ->add( 'p.pseudo = ?1')
            ->add( 'p.team IS NULL' )
        );

        $qb->setParameter( '1', $pseudo );

        return $qb->getQuery()->getOneOrNullResult();
    }
}
