<?php

namespace TeamBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPseudoLike( $pseudo, $inTeam = false ) {
        $qb = $this->createQueryBuilder( 'p' );
        $qb->select( 'p.pseudo' );
        $qb->where($qb->expr()->andX()
            ->add( 'p.pseudo LIKE ?1')
            ->add( $inTeam ? 'p.team IS NOT NULL OR p.team IS NULL' : 'p.team IS NULL' )
        );

        $qb->setParameter( '1', '%'.$pseudo.'%' );

        return $qb->getQuery()->getScalarResult();
    }
}
