<?php

namespace TeamBundle\Repository;

/**
 * SynergieClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SynergieClassRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSynergie( $class1, $class2 ) {
        $qb = $this->createQueryBuilder( 's' );

        $qb->select( 's.points' )
            ->where( $qb->expr()->andX()
                ->add( $qb->expr()->orX()
                    ->add( 's.class1 = :class1' )
                    ->add( 's.class2 = :class1' )
                )
                ->add( $qb->expr()->orX()
                    ->add( 's.class1 = :class2' )
                    ->add( 's.class2 = :class2' )
                )
            )
            ->setParameter( 'class1', $class1 )
            ->setParameter( 'class2', $class2 );

        return $qb->getQuery()->getSingleResult();
    }
}
