<?php

namespace TeamBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function search( $terms, $onlyEdition, $onlyPlayer, $onlyTeam ) {
        $qb = $this->createQueryBuilder( 't' );

        $players = $this->getEntityManager()->getRepository( 'TeamBundle:Player' )->search( $terms );

        if( !$onlyTeam ) {
            $teams = array();
            foreach( $players as $k => $v ) {
                $teams[] = $v->getTeam()->getId();
            }

            if( $teams )
                $qb->orWhere( $qb->expr()->in( 't.id', $teams ) );
        }

        if( !$onlyPlayer ) {
            for( $i = 0; $i < count( $terms ); $i++ )
                $qb->orWhere( 't.name LIKE ?'.$i );
        } else
            $terms = array();

        if( $onlyEdition ) {
            $qb->andWhere( 't.registered = ?' . count($terms) );
            $terms[] = true;
        }

        $qb->setParameters( $terms );

        $qb->orderBy( 't.name', 'ASC' );

        return $qb->getQuery()->getResult();
    }

    public function getList( $page = 1, $maxPerPage = 9 ) {
        $qb = $this->createQueryBuilder( 't' );

        $qb->where( 't.registered=?1' );
        $qb->orderBy( 't.name', 'ASC' );

        $qb->setFirstResult( ( $page - 1 ) * $maxPerPage )
            ->setMaxResults( $maxPerPage );

        $qb->setParameter( 1, true);

        return new Paginator( $qb, false );
    }

    public function resetRegistration() {
        $qb = $this->createQueryBuilder( 't' );

        $qb->update();
        $qb->set( 't.registered', '0' );

        return $qb->getQuery()->execute();
    }
}
