<?php

namespace TeamBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function search( $terms ){
        $qb = $this->createQueryBuilder( 't' );

        $players = $this->getEntityManager()->getRepository( 'TeamBundle:Player' )->search( $terms );

        $teams = array();
        foreach( $players as $k => $v ){
            $teams[] = $v->getTeam()->getId();
        }

        $qb->orWhere( $qb->expr()->in( 't.id', $teams ) );

        for( $i = 0; $i < count( $terms ); $i++ )
            $qb->orWhere( 't.name LIKE ?'.$i );



        //$qb->setParameter( 'teams', $teams );
        $qb->setParameters( $terms );

        return $qb->getQuery()->getResult();
    }
}
