<?php

namespace LogBundle\Repository;

/**
 * ActionLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionLogRepository extends \Doctrine\ORM\EntityRepository
{
}
