<?php

namespace AdminBundle\Repository;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOneBy( $criteria ) {
        $query = $this->createQueryBuilder( 'c' )
            ->select( 'c.value' )
            ->where( 'c.'.key( $criteria ).' = ?1' )
            ->setParameter( 1, current( $criteria ) );

        return $query->getQuery()->getSingleScalarResult();
    }

    public function getOne( $criteria ) {
        $query = $this->createQueryBuilder('c')
            ->select( 's' )
            ->where( 's.'.key( $criteria ).' = ?1' )
            ->from('AdminBundle:Config', 's', 's.name')
            ->setParameter( 1, current( $criteria ) );

        return $query->getQuery()->getResult();
    }

    function getAll() {
        $query = $this->createQueryBuilder('c')
            ->select('s')
            ->from('AdminBundle:Config', 's', 's.name');

        return $query->getQuery()->getResult();
    }
}
