<?php

namespace MainBundle\Repository;

/**
 * EditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastEdition() {
        $qb = $this->createQueryBuilder( 'e' );

        $qb->select( 'e' )
            ->orderBy( 'e.id', 'DESC' )
            ->setMaxResults(1);

        return $qb->getQuery()->getSingleResult();
    }

    public function getDate( $date, $type = null ) {
        if( !is_null( $type ) )
            return $this->findLastEdition()->getData()['date']->$date->$type;
        else
            return $this->findLastEdition()->getData()['date']->$date;
    }
}
