<?php

namespace MatchBundle\Repository;

/**
 * MapDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapDateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMapDate( $date, $edition )
    {
        $qb = $this->createQueryBuilder( 'm' );

        $qb->where( 'm.edition = ?1' );
        $qb->setParameter( '1', $edition );

        $qb->andWhere( 'm.date = ?2' );
        $qb->setParameter( '2', $date->format('Y-m-d') );

        return $qb->getQuery()->getOneOrNullResult();
    }
}
