<?php

namespace MatchBundle\Repository;

/**
 * MatchResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchResultRepository extends \Doctrine\ORM\EntityRepository
{
}
