<?php

namespace MatchBundle\Repository;

/**
 * MatchResultTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchResultTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
