<?php

namespace MatchBundle\Repository;

/**
 * MatchsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchsRepository extends \Doctrine\ORM\EntityRepository
{
    function findByTeam( $id, $ordered = false ) {
        $qb = $this->createQueryBuilder( 'm' );
        $qb->where( $qb->expr()->orX()
            ->add( 'm.attack = ?1' )
            ->add( 'm.defense = ?2' )
        );
        if( $ordered )
            $qb->orderBy( 'm.date ', 'DESC');
        $qb->setParameter( '1', $id );
        $qb->setParameter( '2', $id );

        return $qb->getQuery()->getResult();
    }

    function findByDate( \DateTime $time, $order = array(), $limit = null, $null = true, $withTime = false ) {
        $qb = $this->createQueryBuilder( 'm' );
        if( $null ) {
            $qb->where($qb->expr()->orX()
                ->add( 'm.date >= ?1' )
                ->add( 'm.date IS NULL' )
            );
        } else {
            $qb->where( 'm.date >= ?1' );
        }
        if( !empty( $order ) )
            $qb->orderBy( 'm.'.$order[ 'field' ], $order[ 'type' ] );

        if( $limit )
            $qb->setMaxResults( $limit );

        $qb->setParameter( '1', $time->format( $withTime ? 'Y-m-d H:i' : 'Y-m-d' ) );

        return $qb->getQuery()->getResult();
    }

    function findByDateInf( \DateTime $time, $order = array(), $limit = null, $null = true, $withTime = false ) {
        $qb = $this->createQueryBuilder( 'm' );
        if( $null ) {
            $qb->where($qb->expr()->orX()
                ->add( 'm.date <= ?1' )
                ->add( 'm.date IS NULL' )
            );
        } else {
            $qb->where( 'm.date <= ?1' );
        }
        if( !empty( $order ) )
            $qb->orderBy( 'm.'.$order[ 'field' ], $order[ 'type' ] );

        if( $limit )
            $qb->setMaxResults( $limit );

        $qb->setParameter( '1', $time->format( $withTime? 'Y-m-d H:i' : 'Y-m-d' ) );

        return $qb->getQuery()->getResult();
    }
}
