<?php

namespace NotificationBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function setRead( $user, $maxTime ){
        try {
            $qb = $this->createQueryBuilder( 'n' );

            $qb->update()
                ->set( 'n.timeRead', '?1' )
                ->where($qb->expr()->andX()
                    ->add( 'n.user = ?2' )
                    ->add( 'n.timeCreated <= ?3' )
                    ->add( 'n.timeRead IS NULL' )
                );

            $qb->setParameter( '1', new \DateTime() );
            $qb->setParameter( '2', $user );
            $qb->setParameter( '3', $maxTime );

            $qb->getQuery()->execute();

            return true;
        }
        catch( \Exception $e ){
            throw $e;
        }
    }
}
